[2025-08-27T08:56:32.988+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-27T08:56:32.994+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: unemployment_etl_dag.run_etl manual__2025-08-27T08:56:32.036789+00:00 [queued]>
[2025-08-27T08:56:32.996+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: unemployment_etl_dag.run_etl manual__2025-08-27T08:56:32.036789+00:00 [queued]>
[2025-08-27T08:56:32.996+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-08-27T08:56:33.000+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_etl> on 2025-08-27 08:56:32.036789+00:00
[2025-08-27T08:56:33.003+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=925) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-27T08:56:33.004+0000] {standard_task_runner.py:72} INFO - Started process 927 to run task
[2025-08-27T08:56:33.004+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'unemployment_etl_dag', 'run_etl', 'manual__2025-08-27T08:56:32.036789+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/unemployment_etl_dag.py', '--cfg-path', '/tmp/tmpxe2i802j']
[2025-08-27T08:56:33.005+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask run_etl
[2025-08-27T08:56:33.021+0000] {task_command.py:467} INFO - Running <TaskInstance: unemployment_etl_dag.run_etl manual__2025-08-27T08:56:32.036789+00:00 [running]> on host 6c81a3d5d2a8
[2025-08-27T08:56:33.048+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='unemployment_etl_dag' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T08:56:32.036789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T08:56:32.036789+00:00'
[2025-08-27T08:56:33.049+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-08-27T08:56:33.049+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-08-27T08:56:33.049+0000] {logging_mixin.py:190} INFO - Current task name:run_etl state:running start_date:2025-08-27 08:56:32.994215+00:00
[2025-08-27T08:56:33.049+0000] {logging_mixin.py:190} INFO - Dag name:unemployment_etl_dag and current dag run status:running
[2025-08-27T08:56:33.049+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-27T08:56:33.290+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 225, in run_etl
    save_data(df, records, country, indicator_name)
  File "/opt/airflow/dags/get_data.py", line 184, in save_data
    with open(f'data/raw/{file_name}.json', 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/unemployment_CZ_total_unemployment_rate.json'
[2025-08-27T08:56:33.306+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-08-27T08:56:33.306+0000] {logging_mixin.py:190} INFO - Task start:2025-08-27 08:56:32.994215+00:00 end:2025-08-27 08:56:33.305838+00:00 duration:0.311623
[2025-08-27T08:56:33.306+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_etl> dag:<DAG: unemployment_etl_dag> dagrun:<DagRun unemployment_etl_dag @ 2025-08-27 08:56:32.036789+00:00: manual__2025-08-27T08:56:32.036789+00:00, state:running, queued_at: 2025-08-27 08:56:32.054970+00:00. externally triggered: True>
[2025-08-27T08:56:33.307+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'data/raw/unemployment_CZ_total_unemployment_rate.json'
[2025-08-27T08:56:33.307+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=unemployment_etl_dag, task_id=run_etl, run_id=manual__2025-08-27T08:56:32.036789+00:00, execution_date=20250827T085632, start_date=20250827T085632, end_date=20250827T085633
[2025-08-27T08:56:33.316+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-27T08:56:33.316+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task run_etl ([Errno 2] No such file or directory: 'data/raw/unemployment_CZ_total_unemployment_rate.json'; 927)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 225, in run_etl
    save_data(df, records, country, indicator_name)
  File "/opt/airflow/dags/get_data.py", line 184, in save_data
    with open(f'data/raw/{file_name}.json', 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/unemployment_CZ_total_unemployment_rate.json'
[2025-08-27T08:56:33.360+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-27T08:56:33.375+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T08:56:33.376+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
